<?php

namespace fPHP\Twigs;
use \fPHP\Roots\forestString as forestString;
use \fPHP\Roots\forestList as forestList;
use \fPHP\Roots\forestNumericString as forestNumericString;
use \fPHP\Roots\forestInt as forestInt;
use \fPHP\Roots\forestFloat as forestFloat;
use \fPHP\Roots\forestBool as forestBool;
use \fPHP\Roots\forestArray as forestArray;
use \fPHP\Roots\forestObject as forestObject;
use \fPHP\Roots\forestLookup as forestLookup;
use \fPHP\Helper\forestLookupData;

class testddlTwig extends forestTwig {
	use \fPHP\Roots\forestData;
	
	/* Fields */
	
	private $Id;
	private $UUID;
	private $ShortText;
	private $Text;
	private $SmallInt;
	private $Int;
	private $BigInt;
	private $Timestamp;
	private $Time;
	private $DoubleCol;
	private $Decimal;
	private $Bool;
	private $Text2;
	private $ShortText2;
	
	/* Properties */
	
	/* Methods */
	
	protected function init() {
		$this->Id = new forestNumericString(1);
		$this->UUID = new forestString;
		$this->ShortText = new forestString;
		$this->Text = new forestString;
		$this->SmallInt = new forestInt;
		$this->Int = new forestInt;
		$this->BigInt = new forestInt;
		$this->Timestamp = new forestObject('forestDateTime');
		$this->Time = new forestObject('forestDateTime');
		$this->DoubleCol = new forestFloat;
		$this->Decimal = new forestFloat;
		$this->Bool = new forestBool;
		$this->Text2 = new forestString;
		$this->ShortText2 = new forestString;
		
		/* forestTwig system fields */
		$this->fphp_Table->value = 'sys_fphp_testddl';
		$this->fphp_Primary->value = array('Id');
		$this->fphp_Unique->value = array('UUID','ShortText');
		$this->fphp_Interval->value = 50;
		$this->fphp_View->value = array('ShortText', 'Int');
		$this->fphp_FillMapping(get_object_vars($this));
	}
}

/*

MariaDB

CREATE TABLE `sys_fphp_testddl` (
  `Id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `UUID` varchar(36) NOT NULL UNIQUE,
  `ShortText` varchar(255) NULL,
  `Text` text NULL,
  `SmallInt` smallint(6) NULL,
  `Int` int(10) NULL,
  `BigInt` bigint(20) NULL,
  `Timestamp` datetime NULL,
  `Time` time NULL,
  `DoubleCol` double NULL,
  `Decimal` decimal(10,2) NULL,
  `Bool` bit(1) NULL,
  `Text2` varchar(36) NULL,
  `ShortText2` varchar(255) NULL
);

SQLite3

CREATE TABLE `sys_fphp_testddl` (
  `Id` integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `UUID` varchar(36) NOT NULL UNIQUE,
  `ShortText` varchar(255) NULL,
  `Text` text NULL,
  `SmallInt` smallint(6) NULL,
  `Int` int(10) NULL,
  `BigInt` bigint(20) NULL,
  `Timestamp` datetime NULL,
  `Time` time NULL,
  `DoubleCol` double NULL,
  `Decimal` decimal(10,2) NULL,
  `Bool` bit(1) NULL,
  `Text2` varchar(36) NULL,
  `ShortText2` varchar(255) NULL
);

MSSQL

CREATE TABLE [sys_fphp_testddl] (
  [Id] int NOT NULL PRIMARY KEY IDENTITY(1,1),
  [UUID] nvarchar(36) NOT NULL UNIQUE,
  [ShortText] nvarchar(255) NULL,
  [Text] text NULL,
  [SmallInt] smallint NULL,
  [Int] int NULL,
  [BigInt] bigint NULL,
  [Timestamp] datetime NULL,
  [Time] time NULL,
  [DoubleCol] float NULL,
  [Decimal] decimal(18,2) NULL,
  [Bool] bit NULL,
  [Text2] nvarchar(36) NULL,
  [ShortText2] nvarchar(255) NULL
);

PGSQL

CREATE TABLE "sys_fphp_testddl" (
  "Id" serial PRIMARY KEY,
  "UUID" varchar(36) NOT NULL UNIQUE,
  "ShortText" varchar(255) NULL,
  "Text" text NULL,
  "SmallInt" smallint NULL,
  "Int" integer NULL,
  "BigInt" bigint NULL,
  "Timestamp" timestamp NULL,
  "Time" time NULL,
  "DoubleCol" double precision NULL,
  "Decimal" decimal NULL,
  "Bool" boolean NULL,
  "Text2" varchar(36) NULL,
  "ShortText2" varchar(255) NULL
);

Oracle

CREATE TABLE "sys_fphp_testddl" (
  "Id" NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
  "UUID" VARCHAR2(36) NOT NULL UNIQUE,
  "ShortText" VARCHAR2(255) NULL,
  "Text" CLOB NULL,
  "SmallInt" SMALLINT NULL,
  "Int" INTEGER NULL,
  "BigInt" LONG NULL,
  "Timestamp" TIMESTAMP NULL,
  "Time" INTERVAL DAY(0) TO SECOND(0) NULL,
  "DoubleCol" DOUBLE PRECISION NULL,
  "Decimal" NUMBER(38,2) NULL,
  "Bool" CHAR(1) NULL,
  "Text2" VARCHAR2(36) NULL,
  "ShortText2" VARCHAR2(255) NULL
);
INSERT INTO "SYSTEM"."sys_fphp_testddl" ("UUID","ShortText", "Text", "SmallInt", "Int", "BigInt", "Timestamp", "Time", "DoubleCol", "Decimal", "Bool")
VALUES ('uuid','Test', 'Test Test', 1, 10000, 4821432546, timestamp '2019-06-13 20:29:33', '+0 20:29:29', 3.1413, 15.559, 1);

*/

?>